version: '3.8'
services:
  proxy:
    build:
      context: .
      target: prod
    network_mode: host  # Use host networking to access WireGuard
    environment:
      - LISTEN_HOST=0.0.0.0  # Binds to all interfaces - accessible from WireGuard
      - LISTEN_PORT=11434
      - VERBOSE=1
      - UPSTREAM=http://127.0.0.1:8080
      - THINKING_MODE=show_reasoning
      - THINKING_DEBUG=true
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS -X POST http://localhost:11434/debug/json -d '{}' -H 'Content-Type: application/json' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
